### PR TITLE
Revived the Lua bindings

### PR DESCRIPTION
**Pull request by Mailaender**
Moved from https://github.com/mono/monodevelop/pull/699 as requested.

### CODE REVIEW

**Comment by Therzok** [comment]
/cc @slluis.

I don't have merge rights here. -_-

**Comment by Mailaender** [comment]
Also added a project file to publish at http://addins.monodevelop.com/Project/Index/153 now.

**Comment by Therzok** [comment]
Thanks a lot! You're awesome!

**Comment by slluis** [comment]
Thanks!

**Pull request merged**
